### ISSUE TITLE
Suggestion: Make Pandas dependency optional

### ISSUE THREAD

**Issue by seperman** [alan-turing-institute/CleverCSV#10]
Hello,
First of all thanks for writing this cool library.
Is it possible to make Pandas an optional dependency? From looking at the code briefly, it seems it should work without Pandas too if you are just dealing with reading csv files. There are projects that don't need Pandas but could use this library.
Thanks

**Comment by GjjvdBurg** [comment]
Hi @seperman, thanks for the suggestion! You're correct that the package works without pandas too. Do you have a particular use case in mind where the additional dependency on pandas is problematic? One the one hand I can imagine having a smaller set of dependencies may be useful for some, but for others having the pandas wrappers by default may be very helpful. I'd like to understand both sides well before I make such a change. Let me know! :)

**Comment by seperman** [comment]
Hi @GjjvdBurg 
Sorry I didn't get back to you earlier. Yes I do run into type of work that requires data ingestion and the source of data is often a csv. In such cases there is no need for pandas but the CSV sniffing is always required. This is particularly true for ELT pipelines where the transformations happen after the CSV is extracted and loaded.

**Comment by GjjvdBurg** [comment]
Hi @seperman,

I've created a PR with a potential separation of the package into a core and full version. I'd like to hear your thoughts on this change and whether it addresses your concerns.

Of course, if anyone else seeing this has an opinion on the proposed split, please do let me know.

**Comment by seperman** [comment]
Hi @GjjvdBurg 
Thanks for the PR. It looks good. I left some minor comments.

**Comment by GjjvdBurg** [comment]
Fixed in version 0.6.0. Thanks for the suggestion @seperman!

**Comment by seperman** [comment]
Thanks @GjjvdBurg !
