### ISSUE TITLE
Wheels for Python 3.13

### ISSUE THREAD

**Issue by jodal** [alan-turing-institute/CleverCSV#139]
Python 3.13.0 was released six weeks ago.

It would be great if you could upload wheels built for Python 3.13, either of version 0.8.2 or of a new release, so that Python 3.13 users can install CleverCSV without having a build toolchain installed.

**Comment by GjjvdBurg** [comment]
Thanks for the reminder @jodal, wheels for 3.13 are available now on PyPI
