### ISSUE TITLE
Error: field larger than field limit (131072)

### ISSUE THREAD

**Issue by Naviden** [alan-turing-institute/CleverCSV#21]
Hi, using the `clevercsv code`, I get the following code:

```
import clevercsv

with open("./sample_train_postings.csv", "r", newline="", encoding="utf-8") as fp:
    reader = clevercsv.reader(fp, delimiter="\t", quotechar="`", escapechar="")
    rows = list(reader)
```

Which in turn gives me this error:

`Error: field larger than field limit (131072)`

Any idea how to handle this?

**Comment by GjjvdBurg** [comment]
Please reopen the issue if it's still a problem for you.
