### ISSUE TITLE
undefined symbol: PyUnicode_ReadChar

### ISSUE THREAD

**Issue by seperman** [alan-turing-institute/CleverCSV#25]
Hello,
I'm getting an undefined symbol error when using Clevercsv on pypy3.

`clevercsv/cparser.pypy3-71-x86_64-linux-gnu.so: undefined symbol: PyUnicode_ReadChar`

Here are some examples:
https://travis-ci.org/github/seperman/deepdiff/jobs/731069534

Looking at the code, it doesn't seem you are officially supporting pypy3 but I figured to put it here in case you decide to support it.
Thanks.

**Comment by GjjvdBurg** [comment]
Hi @seperman,

Thanks for reporting this issue. I'm aware that CleverCSV doesn't compile on PyPy, and this mainly has to do with the fact that we have a custom CSV parser written in C/CPython. While it would technically be possible to write this parser in pure Python and fall back to that when the C parser is not available, this is not a trivial addition so I don't have plans to add that at this time (although I'm happy to consider pull requests). So for now I'll mark this as wontfix and close the issue, but I hope the clarification helps.

Thanks again!

**Comment by seperman** [comment]
Hi, Ok. Thanks for explaining.
