### ISSUE TITLE
Understanding the licensing

### ISSUE THREAD

**Issue by hyandell** [alan-turing-institute/CleverCSV#33]
Hi CleverCSV folk,

I was wondering how to consider the licensing of CleverCSV.

The LICENSE file says the project is MIT, but the src/abstraction.csv file says GPL-2.0. Is one an error?

**Comment by GjjvdBurg** [comment]
Hi @hyandell, thanks for raising this issue. The latter is indeed an error, the code is licensed under the MIT license. I've now fixed this in the master branch and clarified it in the readme. Thanks again!

**Comment by hyandell** [comment]
Thank you!
