### ISSUE TITLE
help for data type detection 

### ISSUE THREAD

**Issue by hcheng2002cn** [alan-turing-institute/CleverCSV#34]
CleverCSV looks very promising !
I try to use this package to extract csv to database. We need detect datatype of each column. Is there anyway this package can help ?
The other question, is it possible(performance/memory) we can handle multi GB data by using this package ?

Thanks for help.
hong

**Comment by GjjvdBurg** [comment]
Hi @hcheng2002cn,

Thanks for your interest in this package! You could use the type detection functionality included in the [TypeDetector](https://github.com/alan-turing-institute/CleverCSV/blob/a9103f633adaaeb20509241d233ad0cb62ba11f7/clevercsv/detect_type.py#L116) class. This is a regular-expression based type detection approach that supports a number of basic data types. I have never tried to use it on multiple GBs of data, so I can't say how fast/slow it'll be.

Alternatively, you might be interested in the [ptype](https://github.com/alan-turing-institute/ptype) package by my colleagues. This is a _probabilistic_ approach to data type detection that gives a distribution over likely data types.

If you do use any of these packages, I would be curious to hear your experience!

**Comment by hcheng2002cn** [comment]
@GjjvdBurg Thanks for you quick response. will try out those package and let you know the feedback.

**Comment by hcheng2002cn** [comment]
look like CleverCSV only support file open with TEXT mode? when we try open file using "rb" or "wb" got exception TypeError: a bytes-like object is required, not 'str'.
Any reason for that ?
Thanks.

**Comment by GjjvdBurg** [comment]
Yes, that sounds reasonable. We detect the file encoding using [get_encoding](https://github.com/alan-turing-institute/CleverCSV/blob/a9103f633adaaeb20509241d233ad0cb62ba11f7/clevercsv/utils.py#L22) and then open the file for reading in the proper encoding (like [this](https://github.com/alan-turing-institute/CleverCSV/blob/a9103f633adaaeb20509241d233ad0cb62ba11f7/clevercsv/wrappers.py#L304) for example).

Are you expecting binary data in the CSV file? Otherwise I think detecting the encoding is probably the way to go.

**Comment by hcheng2002cn** [comment]
I got a csv file:

"{""fake"": ""json"", ""fake2"":""json2""}",1,abc
"{""fake"": ""json"", ""fake2"":""json2""}",1,abc
"{""fake"": ""json"", ""fake2"":""json2""}",1,abc
"{""fake"": ""json"", ""fake2"":""json2""}",1,abc

Seem it can not sniff the dialect.

**Comment by hcheng2002cn** [comment]
We found below csv can not detect dialect:
"{""fake"": ""json"", ""fake2"":""json2""}", 1, abc
"{""fake"": ""json"", ""fake2"":""json2""}", 1, abc
"{""fake"": ""json"", ""fake2"":""json2""}", 1, abc
Would you please help to take a look ? 

Thanks
hong

**Comment by GjjvdBurg** [comment]
Hi @hcheng2002cn,

I'm sorry to hear that! Unfortunately I can't seem to reproduce the error:

```
$ cat test.csv 
"{""fake"": ""json"", ""fake2"":""json2""}", 1, abc
"{""fake"": ""json"", ""fake2"":""json2""}", 1, abc
"{""fake"": ""json"", ""fake2"":""json2""}", 1, abc
$ clevercsv detect -v test.csv 
Running normal form detection ...
Matched normal form 3.
Detected: SimpleDialect(',', '"', '')
```

Can you share an example of your code where this doesn't work?

**Comment by hcheng2002cn** [comment]
ah, this works now. thanks.
I have problem for sample:
"{""fake"": ""json"", ""fake2"":""json2""}"

which return None for dialect, look reasonable. 

Thanks for help.

**Comment by GjjvdBurg** [comment]
Glad to hear it works. That last sample is indeed difficult to parse as a CSV file :)

**Comment by GjjvdBurg** [comment]
Closing this issue as I think it's solved. If there's more to discuss please reopen.
