### ISSUE TITLE
Is there a way to distinguish between ,, and ,"", in the reader?

### ISSUE THREAD

**Issue by zt-initech** [alan-turing-institute/CleverCSV#38]
PostgreSQL RDBMS has CSV export/import functionality (https://www.postgresql.org/docs/9.6/sql-copy.html) that has a quirk in its CSV format: they treat `,,` as SQL NULL and `,"",` as a zero length string value. These are different values, and it is important to be able to distinguish between them.

Is there a way to parse a line like `foo,,bar,"",baz` as `['foo', None, bar, '', 'baz']` ? Without forking and playing with the state machine in C, of course. :-)

**Comment by zt-initech** [comment]
Thanks for the hint! I came up with the following:

```
from clevercsv import field_size_limit
from clevercsv.cparser import Parser, Error as ParserError
from clevercsv.exceptions import Error
from clevercsv.read import reader


class MyCSVReader(reader):
    def __iter__(self):
        self.parser_gen = Parser(
            self.csvfile,
            delimiter=self.dialect.delimiter,
            quotechar=self.dialect.quotechar,
            escapechar=self.dialect.escapechar,
            field_limit=field_size_limit(),
            strict=self.dialect.strict,
            return_quoted=True,
        )
        return self
    def __next__(self):
        if self.parser_gen is None:
            self.__iter__()
        try:
            row = next(self.parser_gen)
        except ParserError as e:
            raise Error(str(e))
        self.line_num += 1
        transformed_row = []
        for v, was_quoted in row:
            if v == '' and not was_quoted:
                v = None
            transformed_row.append(v)
        return transformed_row


from clevercsv.dialect import SimpleDialect
dialect = SimpleDialect(',', '"', '')
with open('myfile', encoding='UTF-8') as f:
    rows = list(MyCSVReader(f))

```

This gives me the values I want in my rows (`None` for `,,`).
Is there a better way to accomplish the same thing? 

Now I need to find a way to produce files in the same format, i.e. quote zero length string but not quote None. Do you have hints for that?

**Comment by GjjvdBurg** [comment]
Hi @zt-initech, I think your solution looks great!

Regarding writing files in that format, we actually defer to the Python ``csv.writer`` in CleverCSV, so there's nothing build into the package that could help. You could write your own function to turn a row into string, and quote all strings except None. This wouldn't be particularly complicated, but you'd have to handle quote collision. Something like this might get you started:

```python
def handle_cell(c):
    if c is None:
        return ''
    if not isinstance(c, str):
        c = str(c)  
    if '"' in c:
        c = c.replace('"', '""')
    return f'"{c}"'

def handle_row(r):
    return ','.join(map(handle_cell, r))
```

You might want to set up a few unit tests that check that you can reliably do a round-trip with this writing functionality and the above reader. Hope this helps!
