### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [alan-turing-institute/CleverCSV#39]
Problem
---------
On aarch64, pip install CleverCSV builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install CleverCSV should download the wheels from pypi

@GjjvdBurg , Please let me know your interest on releasing aarch64 wheels. I can help in this.

**Comment by GjjvdBurg** [comment]
Hi @odidev, aarch64 wheels are now available for CleverCSV version 0.7.0.
