### ISSUE TITLE
Built-in support for cChardet

### ISSUE THREAD

**Issue by cstork** [alan-turing-institute/CleverCSV#48]
I noticed that in my applications most of the runtime of CleverCSV is used up by chardet. Since [uChardet](https://github.com/PyYoshi/cChardet) is much faster it might be worth supporting it by default. (I know that it's possible to determine the encoding first with cChardet and then pass it to CleverCSV. I'm just suggesting this as a possible enhancement – maybe also for people not aware of cChardet.)

**Comment by GjjvdBurg** [comment]
Thanks for suggesting this @cstork, I'll take a look!

**Comment by GjjvdBurg** [comment]
I've added cChardet as an optional dependency, so it'll be used when it's available on the system. Hope this helps!
