### ISSUE TITLE
Please consider signing new tags

### ISSUE THREAD

**Issue by baldurmen** [alan-turing-institute/CleverCSV#50]
Hello!

I'm currently working on [packaging this library in Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1003035).

It would be very nice if in the future, you could sign new tags with an OpenPGP key. It's not much more work and it provides a very clear trust chain:

https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work

Thanks in advance,

**Comment by GjjvdBurg** [comment]
Hi @baldurmen, thanks for raising this issue and packaging clevercsv for Debian! I'll look into signing new tags from now on, thanks!
