### ISSUE TITLE
delimiter detection error

### ISSUE THREAD

**Issue by tooptoop4** [alan-turing-institute/CleverCSV#58]
For a pipe delimited file it is being detected as space delimited when i feed in around 1000 rows (however csv lib correctly detects pipe), if i only feed in 100 rows then clevercsv is also able to detect pipe

ie like below data but 55 columns wide
"Private Company"|"Point Rd"

**Comment by GjjvdBurg** [comment]
Hi @tooptoop4, thanks for reporting this issue. Are you able to share the file? I may be able to fix the problem

**Comment by tooptoop4** [comment]
unfortunately it contains private data

**Comment by tooptoop4** [comment]
i have another case where 100 rows seems more accurate (it correctly picks , ) but 1200 rows picks \

**Comment by GjjvdBurg** [comment]
Results can be a bit noisy if you don't read the entire file. Theoretically, it might be the case that the "key" to reading the file correctly is only the last row. Therefore, if time allows, it's generally recommended to detect the dialect using the entire file. If you have a case where detection fails on the entire file, please let me know

**Comment by ws-garcia** [comment]
Hi @tooptoop4. Dialect detection is so hard. You can exclude space character potential dialects from the list of candidates. How ever, you can try [this similar approach](https://content.iospress.com/articles/data-science/ds240062) to attempt infer dialects from python.

**Comment by GjjvdBurg** [comment]
I'm closing this issue as addressing dialect detection in this specific instance would require an example of the file. Please open a new issue if such an example file can be shared.
