### ISSUE TITLE
precedence for delimiter characters?

### ISSUE THREAD

**Issue by tooptoop4** [alan-turing-institute/CleverCSV#69]
right now it is incorrectly guessing _ character, can I give a precedence set of delimiters like ,|\t ?

**Comment by GjjvdBurg** [comment]
Hi @tooptoop4, you can set the delimiters to consider in the [Detector.detect](https://clevercsv.readthedocs.io/en/latest/source/clevercsv.html#clevercsv.detect.Detector.detect) method. This is not exactly the same as precedence, but it will restrict the set of options.
