### ISSUE TITLE
Unexpected exceptions on many inputs

### ISSUE THREAD

**Issue by flopp** [alan-turing-institute/CleverCSV#7]
I ran `pythonfuzz` on `clevercsv`'s detection engine, and got many input samples resulting in unexpected exceptions, e.g. a file just containing three double-quotes results in a `SystemError`:

```
clevercsv detect doublequote-doublequote-doublequote.csv 

[SystemError]
PyEval_EvalFrameEx returned a result with an error set
```

I'm using `clevercsv 0.5.3` from `pypi` with `Python 3.7` running on `Ubuntu 19.10`.

I've attached a ZIP file containing the fuzzing script and some sample input files leading to unexpected exceptions.

[clevercsv-fuzzing.zip](https://github.com/alan-turing-institute/CleverCSV/files/4059140/clevercsv-fuzzing.zip)

**Comment by GjjvdBurg** [comment]
Thanks for letting me know @flopp! I'll take a look

**Comment by GjjvdBurg** [comment]
@flopp Thanks again for letting me know about this bug! It's now fixed in master and I'll prepare a release right away.
